#!/usr/bin/env bash

# shellcheck disable=SC1091
. ../libis

func() { :; }

unset undefined

# shellcheck disable=SC2034
arr=(abc)

# shellcheck disable=SC2034
declare -A assoc

# shellcheck disable=SC2034
arr_empty=()

# shellcheck disable=SC2034
str="abc"

# shellcheck disable=SC2034
str_empty=""
